/**
 * @file BackendManifestTemplates.cpp
 * @author Gaspard Kirira
 *
 * Copyright 2025, Gaspard Kirira.  All rights reserved.
 * https://github.com/vixcpp/vix
 * Use of this source code is governed by a MIT license
 * that can be found in the License file.
 */

#include <vix/cli/commands/new/templates/backend/BackendManifestTemplates.hpp>

#include <string>

namespace vix::commands::new_cmd::templates
{

  std::string make_project_manifest_backend(
      const std::string &projectName,
      const FeaturesSelection &features)
  {
    std::string s;
    s.reserve(3000);

    s += "# Vix backend application manifest\n";
    s += "# This file is read by Vix and converted to an internal CMake project.\n";
    s += "# The generated CMakeLists.txt lives under .vix/generated/app/.\n\n";

    s += "name = \"" + projectName + "\"\n";
    s += "type = \"executable\"\n";
    s += "standard = \"c++20\"\n\n";

    s += "sources = [\n";
    s += "  \"src/main.cpp\",\n";
    s += "  \"src/" + projectName + "/app/AppBootstrap.cpp\",\n";
    s += "  \"src/" + projectName + "/presentation/routes/RouteRegistry.cpp\",\n";
    s += "  \"src/" + projectName + "/presentation/middleware/MiddlewareRegistry.cpp\",\n";
    s += "  \"src/" + projectName + "/presentation/controllers/HealthController.cpp\",\n";
    s += "]\n\n";

    s += "include_dirs = [\n";
    s += "  \"src\",\n";
    s += "]\n\n";

    s += "defines = [\n";
    s += "  \"VIX_BACKEND_APP=1\",\n";

    if (features.orm)
      s += "  \"VIX_USE_ORM=1\",\n";
    if (features.sanitizers)
      s += "  \"VIX_SANITIZERS=1\",\n";
    if (features.static_rt)
      s += "  \"VIX_LINK_STATIC=1\",\n";
    if (features.full_static)
      s += "  \"VIX_LINK_FULL_STATIC=1\",\n";

    s += "]\n\n";

    s += "compile_options = [\n";
    s += "  \"$<$<CXX_COMPILER_ID:MSVC>:/W4>\",\n";
    s += "  \"$<$<CXX_COMPILER_ID:MSVC>:/permissive->\",\n";
    s += "  \"$<$<NOT:$<CXX_COMPILER_ID:MSVC>>:-Wall>\",\n";
    s += "  \"$<$<NOT:$<CXX_COMPILER_ID:MSVC>>:-Wextra>\",\n";
    s += "  \"$<$<NOT:$<CXX_COMPILER_ID:MSVC>>:-Wpedantic>\",\n";

    if (features.sanitizers)
    {
      s += "  \"$<$<NOT:$<CXX_COMPILER_ID:MSVC>>:-g3>\",\n";
      s += "  \"$<$<NOT:$<CXX_COMPILER_ID:MSVC>>:-fno-omit-frame-pointer>\",\n";
      s += "  \"$<$<NOT:$<CXX_COMPILER_ID:MSVC>>:-O1>\",\n";
      s += "  \"$<$<NOT:$<CXX_COMPILER_ID:MSVC>>:-fsanitize=address,undefined>\",\n";
      s += "  \"$<$<NOT:$<CXX_COMPILER_ID:MSVC>>:-fno-sanitize-recover=undefined>\",\n";
    }

    s += "]\n\n";

    s += "link_options = [\n";

    if (features.sanitizers)
    {
      s += "  \"$<$<NOT:$<CXX_COMPILER_ID:MSVC>>:-g>\",\n";
      s += "  \"$<$<NOT:$<CXX_COMPILER_ID:MSVC>>:-fsanitize=address,undefined>\",\n";
    }

    if (features.full_static)
      s += "  \"$<$<NOT:$<CXX_COMPILER_ID:MSVC>>:-static>\",\n";
    else if (features.static_rt)
    {
      s += "  \"$<$<NOT:$<CXX_COMPILER_ID:MSVC>>:-static-libstdc++>\",\n";
      s += "  \"$<$<NOT:$<CXX_COMPILER_ID:MSVC>>:-static-libgcc>\",\n";
    }

    s += "]\n\n";

    s += "compile_features = [\n";
    s += "  \"cxx_std_20\",\n";
    s += "]\n\n";

    s += "packages = [\n";
    s += "  \"vix\",\n";
    s += "]\n\n";

    s += "links = [\n";
    s += "  \"vix::vix\",\n";

    if (features.orm)
      s += "  \"vix::orm\",\n";

    s += "]\n\n";

    s += "resources = [\n";
    s += "  \".env=.env\",\n";
    s += "  \"config=config\",\n";
    s += "  \"public=public\",\n";
    s += "  \"storage=storage\",\n";
    s += "]\n\n";

    s += "output_dir = \"bin\"\n";

    return s;
  }

  std::string make_vix_json_backend(const std::string &projectName)
  {
    std::string s;
    s.reserve(2200);

    s += "{\n";
    s += "  \"name\": \"" + projectName + "\",\n";
    s += "  \"version\": \"0.1.0\",\n";
    s += "  \"type\": \"application\",\n";
    s += "  \"template\": \"backend\",\n";
    s += "  \"description\": \"Production backend application generated by Vix.\",\n";
    s += "  \"license\": \"MIT\",\n";
    s += "  \"deps\": [],\n";
    s += "  \"tasks\": {\n";
    s += "    \"dev\": \"vix run\",\n";
    s += "    \"build\": \"vix build\",\n";
    s += "    \"test\": \"vix tests\",\n";
    s += "    \"health\": \"curl http://localhost:8080/health\"\n";
    s += "  },\n";
    s += "  \"production\": {\n";
    s += "    \"service\": \"" + projectName + "\",\n";
    s += "    \"health_local\": \"http://127.0.0.1:8080/health\",\n";
    s += "    \"logs_on_failure\": true\n";
    s += "  }\n";
    s += "}\n";

    return s;
  }

} // namespace vix::commands::new_cmd::templates
