/**
 * @file BackendManifestTemplates.cpp
 * @author Gaspard Kirira
 *
 * Copyright 2025, Gaspard Kirira.  All rights reserved.
 * https://github.com/vixcpp/vix
 * Use of this source code is governed by a MIT license
 * that can be found in the License file.
 */

#include <vix/cli/commands/new/templates/backend/BackendManifestTemplates.hpp>

#include <string>

namespace vix::commands::new_cmd::templates
{

  std::string make_project_manifest_backend(
      const std::string &projectName,
      const FeaturesSelection &features)
  {
    std::string s;
    s.reserve(5000);

    s += "# Vix backend application manifest\n";
    s += "# This file describes one executable backend target.\n";
    s += "# Vix converts it to an internal CMake project under .vix/generated/app/.\n\n";

    s += "name = \"" + projectName + "\"\n";
    s += "type = \"executable\"\n";
    s += "standard = \"c++20\"\n";
    s += "output_dir = \"bin\"\n\n";

    s += "sources = [\n";
    s += "  \"src/main.cpp\",\n";
    s += "  \"src/" + projectName + "/app/AppBootstrap.cpp\",\n";
    s += "  \"src/" + projectName + "/support/HttpResponses.cpp\",\n";
    s += "  \"src/" + projectName + "/presentation/routes/RouteRegistry.cpp\",\n";
    s += "  \"src/" + projectName + "/presentation/middleware/MiddlewareRegistry.cpp\",\n";
    s += "  \"src/" + projectName + "/presentation/controllers/HomeController.cpp\",\n";
    s += "  \"src/" + projectName + "/presentation/controllers/HealthController.cpp\",\n";
    s += "]\n\n";

    s += "include_dirs = [\n";
    s += "  \"include\",\n";
    s += "  \"src\",\n";
    s += "]\n\n";

    s += "defines = [\n";
    s += "  \"VIX_BACKEND_APP=1\",\n";
    s += "  \"VIX_APP_NAME=" + projectName + "\",\n";

    if (features.orm)
      s += "  \"VIX_USE_ORM=1\",\n";
    if (features.sanitizers)
      s += "  \"VIX_SANITIZERS=1\",\n";
    if (features.static_rt)
      s += "  \"VIX_LINK_STATIC=1\",\n";
    if (features.full_static)
      s += "  \"VIX_LINK_FULL_STATIC=1\",\n";

    s += "]\n\n";

    s += "compile_options = [\n";
    s += "  \"$<$<CXX_COMPILER_ID:MSVC>:/W4>\",\n";
    s += "  \"$<$<CXX_COMPILER_ID:MSVC>:/permissive->\",\n";
    s += "  \"$<$<NOT:$<CXX_COMPILER_ID:MSVC>>:-Wall>\",\n";
    s += "  \"$<$<NOT:$<CXX_COMPILER_ID:MSVC>>:-Wextra>\",\n";
    s += "  \"$<$<NOT:$<CXX_COMPILER_ID:MSVC>>:-Wpedantic>\",\n";

    if (features.sanitizers)
    {
      s += "  \"$<$<NOT:$<CXX_COMPILER_ID:MSVC>>:-g3>\",\n";
      s += "  \"$<$<NOT:$<CXX_COMPILER_ID:MSVC>>:-fno-omit-frame-pointer>\",\n";
      s += "  \"$<$<NOT:$<CXX_COMPILER_ID:MSVC>>:-O1>\",\n";
      s += "  \"$<$<NOT:$<CXX_COMPILER_ID:MSVC>>:-fsanitize=address,undefined>\",\n";
      s += "  \"$<$<NOT:$<CXX_COMPILER_ID:MSVC>>:-fno-sanitize-recover=undefined>\",\n";
    }

    s += "]\n\n";

    s += "link_options = [\n";

    if (features.sanitizers)
    {
      s += "  \"$<$<NOT:$<CXX_COMPILER_ID:MSVC>>:-g>\",\n";
      s += "  \"$<$<NOT:$<CXX_COMPILER_ID:MSVC>>:-fsanitize=address,undefined>\",\n";
    }

    if (features.full_static)
      s += "  \"$<$<NOT:$<CXX_COMPILER_ID:MSVC>>:-static>\",\n";
    else if (features.static_rt)
    {
      s += "  \"$<$<NOT:$<CXX_COMPILER_ID:MSVC>>:-static-libstdc++>\",\n";
      s += "  \"$<$<NOT:$<CXX_COMPILER_ID:MSVC>>:-static-libgcc>\",\n";
    }

    s += "]\n\n";

    s += "compile_features = [\n";
    s += "  \"cxx_std_20\",\n";
    s += "]\n\n";

    s += "packages = [\n";
    s += "  \"vix\",\n";
    s += "]\n\n";

    s += "links = [\n";
    s += "  \"vix::vix\",\n";

    if (features.orm)
      s += "  \"vix::orm\",\n";

    s += "]\n\n";

    s += "resources = [\n";
    s += "  \".env=.env\",\n";
    s += "  \"public=public\",\n";
    s += "  \"views=views\",\n";
    s += "  \"storage=storage\",\n";
    s += "]\n";

    return s;
  }

  std::string make_vix_json_backend(const std::string &projectName)
  {
    std::string s;
    s.reserve(7200);

    s += "{\n";
    s += "  \"name\": \"" + projectName + "\",\n";
    s += "  \"version\": \"0.1.0\",\n";
    s += "  \"type\": \"application\",\n";
    s += "  \"template\": \"backend\",\n";
    s += "  \"description\": \"Production backend application generated by Vix.\",\n";
    s += "  \"license\": \"MIT\",\n";
    s += "  \"deps\": [],\n";
    s += "  \"tasks\": {\n";
    s += "    \"dev\": \"vix dev\",\n";
    s += "    \"build\": \"vix build\",\n";
    s += "    \"check\": \"vix check --tests --run\",\n";
    s += "    \"test\": \"vix tests\",\n";
    s += "    \"env\": \"vix env check\",\n";
    s += "    \"health\": \"vix health\",\n";
    s += "    \"logs\": \"vix logs\",\n";
    s += "    \"service\": \"vix service status\",\n";
    s += "    \"proxy\": \"vix proxy nginx check\",\n";
    s += "    \"doctor\": \"vix doctor production\",\n";
    s += "    \"deploy\": \"vix deploy\",\n";
    s += "    \"orm:status\": \"vix orm status\",\n";
    s += "    \"orm:migrate\": \"vix orm migrate\",\n";
    s += "    \"orm:rollback\": \"vix orm rollback --steps 1\"\n";
    s += "  },\n";
    s += "  \"production\": {\n";
    s += "    \"service\": {\n";
    s += "      \"name\": \"" + projectName + "\",\n";
    s += "      \"user\": \"\",\n";
    s += "      \"working_dir\": \".\",\n";
    s += "      \"exec\": \"bin/" + projectName + "\",\n";
    s += "      \"restart\": \"always\",\n";
    s += "      \"restart_sec\": 3,\n";
    s += "      \"limit_nofile\": 65535\n";
    s += "    },\n";
    s += "    \"ports\": {\n";
    s += "      \"http\": 8080,\n";
    s += "      \"websocket\": 9090\n";
    s += "    },\n";
    s += "    \"websocket\": {\n";
    s += "      \"host\": \"127.0.0.1\",\n";
    s += "      \"port\": 9090,\n";
    s += "      \"path\": \"/ws\",\n";
    s += "      \"local_url\": \"ws://127.0.0.1:9090/ws\",\n";
    s += "      \"public_url\": \"\",\n";
    s += "      \"timeout_ms\": 5000,\n";
    s += "      \"heartbeat\": true\n";
    s += "    },\n";
    s += "    \"proxy\": {\n";
    s += "      \"type\": \"nginx\",\n";
    s += "      \"domain\": \"\",\n";
    s += "      \"tls\": false,\n";
    s += "      \"websocket_path\": \"/ws\",\n";
    s += "      \"certificate\": \"\",\n";
    s += "      \"certificate_key\": \"\"\n";
    s += "    },\n";
    s += "    \"health\": {\n";
    s += "      \"service\": \"" + projectName + "\",\n";
    s += "      \"local\": \"http://127.0.0.1:8080/health\",\n";
    s += "      \"public\": \"\",\n";
    s += "      \"websocket\": \"\",\n";
    s += "      \"expected_status\": 200,\n";
    s += "      \"timeout_ms\": 2000,\n";
    s += "      \"max_response_ms\": 1000\n";
    s += "    },\n";
    s += "    \"deploy\": {\n";
    s += "      \"pull\": true,\n";
    s += "      \"branch\": \"main\",\n";
    s += "      \"build\": \"vix build\",\n";
    s += "      \"tests\": false,\n";
    s += "      \"test_command\": \"vix tests\",\n";
    s += "      \"service\": \"" + projectName + "\",\n";
    s += "      \"health_local\": true,\n";
    s += "      \"health_public\": false,\n";
    s += "      \"proxy_check\": true,\n";
    s += "      \"proxy_reload\": false,\n";
    s += "      \"logs_on_failure\": true,\n";
    s += "      \"log_lines\": 80,\n";
    s += "      \"rollback\": false\n";
    s += "    },\n";
    s += "    \"logs\": {\n";
    s += "      \"service\": \"" + projectName + "\",\n";
    s += "      \"nginx_access\": \"/var/log/nginx/" + projectName + ".access.log\",\n";
    s += "      \"nginx_error\": \"/var/log/nginx/" + projectName + ".error.log\",\n";
    s += "      \"lines\": 120\n";
    s += "    },\n";
    s += "    \"env\": {\n";
    s += "      \"required\": [\n";
    s += "        \"APP_NAME\",\n";
    s += "        \"APP_ENV\",\n";
    s += "        \"SERVER_PORT\",\n";
    s += "        \"DATABASE_ENGINE\",\n";
    s += "        \"DATABASE_SQLITE_PATH\"\n";
    s += "      ]\n";
    s += "    },\n";
    s += "    \"database\": {\n";
    s += "      \"engine\": \"sqlite\",\n";
    s += "      \"sqlite_path\": \"storage/" + projectName + ".db\",\n";
    s += "      \"migrations\": \"migrations\"\n";
    s += "    }\n";
    s += "  }\n";
    s += "}\n";

    return s;
  }

} // namespace vix::commands::new_cmd::templates
