/**
 * @file BackendReadmeTemplates.cpp
 * @author Gaspard Kirira
 *
 * Copyright 2025, Gaspard Kirira. All rights reserved.
 * https://github.com/vixcpp/vix
 * Use of this source code is governed by a MIT license
 * that can be found in the License file.
 */

#include <vix/cli/commands/new/templates/backend/BackendReadmeTemplates.hpp>

namespace vix::commands::new_cmd::templates
{

  std::string make_readme_backend(const std::string &projectName)
  {
    std::string readme;
    readme.reserve(9000);

    readme += "# " + projectName + "\n\n";
    readme += "Production-oriented Vix backend application.\n\n";

    readme += "This project is generated by:\n\n";
    readme += "```bash\n";
    readme += "vix new " + projectName + " --template backend\n";
    readme += "```\n\n";

    readme += "It is designed as a simple production backend starter built around:\n\n";
    readme += "- `vix::App`\n";
    readme += "- `vix.app`\n";
    readme += "- `.env` configuration\n";
    readme += "- route and middleware registries\n";
    readme += "- JSON health endpoints\n";
    readme += "- public static files\n";
    readme += "- production diagnostics\n\n";

    readme += "## Quick start\n\n";
    readme += "```bash\n";
    readme += "cd " + projectName + "\n";
    readme += "cp .env.example .env\n";
    readme += "vix dev\n";
    readme += "```\n\n";

    readme += "Open:\n\n";
    readme += "```txt\n";
    readme += "http://127.0.0.1:8080\n";
    readme += "```\n\n";

    readme += "Check the API:\n\n";
    readme += "```bash\n";
    readme += "curl http://127.0.0.1:8080/api\n";
    readme += "curl http://127.0.0.1:8080/health\n";
    readme += "curl http://127.0.0.1:8080/api/health\n";
    readme += "```\n\n";

    readme += "## Project layout\n\n";
    readme += "```txt\n";
    readme += "include/" + projectName + "/\n";
    readme += "  app/\n";
    readme += "    AppBootstrap.hpp\n";
    readme += "  support/\n";
    readme += "    HttpResponses.hpp\n";
    readme += "\n";
    readme += "src/\n";
    readme += "  main.cpp\n";
    readme += "  " + projectName + "/\n";
    readme += "    app/\n";
    readme += "      AppBootstrap.cpp\n";
    readme += "    application/\n";
    readme += "    domain/\n";
    readme += "    infrastructure/\n";
    readme += "    presentation/\n";
    readme += "      controllers/\n";
    readme += "        HomeController.hpp\n";
    readme += "        HomeController.cpp\n";
    readme += "        HealthController.hpp\n";
    readme += "        HealthController.cpp\n";
    readme += "      middleware/\n";
    readme += "        MiddlewareRegistry.hpp\n";
    readme += "        MiddlewareRegistry.cpp\n";
    readme += "      routes/\n";
    readme += "        RouteRegistry.hpp\n";
    readme += "        RouteRegistry.cpp\n";
    readme += "    support/\n";
    readme += "      HttpResponses.cpp\n";
    readme += "\n";
    readme += "public/\n";
    readme += "  index.html\n";
    readme += "  app.css\n";
    readme += "  app.js\n";
    readme += "\n";
    readme += "views/\n";
    readme += "storage/\n";
    readme += "migrations/\n";
    readme += "tests/\n";
    readme += "config/\n";
    readme += "  production.json\n";
    readme += "\n";
    readme += ".env.example\n";
    readme += "vix.app\n";
    readme += "vix.json\n";
    readme += "README.md\n";
    readme += "```\n\n";

    readme += "## Entry point\n\n";
    readme += "`main.cpp` stays minimal. The application bootstrapping logic lives in `AppBootstrap`.\n\n";

    readme += "```cpp\n";
    readme += "#include <" + projectName + "/app/AppBootstrap.hpp>\n\n";
    readme += "int main()\n";
    readme += "{\n";
    readme += "  " + projectName + "::app::AppBootstrap bootstrap;\n";
    readme += "  return bootstrap.run();\n";
    readme += "}\n";
    readme += "```\n\n";

    readme += "## Application bootstrap\n\n";
    readme += "`AppBootstrap` creates the Vix app, loads `.env`, mounts public files, enables templates, registers middleware, registers routes, and starts the server.\n\n";

    readme += "```txt\n";
    readme += "main.cpp\n";
    readme += "  -> AppBootstrap\n";
    readme += "      -> vix::config::Config\n";
    readme += "      -> vix::App\n";
    readme += "      -> static files\n";
    readme += "      -> templates\n";
    readme += "      -> MiddlewareRegistry\n";
    readme += "      -> RouteRegistry\n";
    readme += "      -> app.run(cfg)\n";
    readme += "```\n\n";

    readme += "## Routes\n\n";
    readme += "Routes are registered from:\n\n";
    readme += "```txt\n";
    readme += "src/" + projectName + "/presentation/routes/RouteRegistry.cpp\n";
    readme += "```\n\n";

    readme += "Generated routes:\n\n";
    readme += "```txt\n";
    readme += "GET /api\n";
    readme += "GET /health\n";
    readme += "GET /api/health\n";
    readme += "```\n\n";

    readme += "The `/` route is served from `public/index.html` through the static file handler.\n\n";

    readme += "## Middleware\n\n";
    readme += "Middleware is registered from:\n\n";
    readme += "```txt\n";
    readme += "src/" + projectName + "/presentation/middleware/MiddlewareRegistry.cpp\n";
    readme += "```\n\n";

    readme += "The generated middleware registry installs:\n\n";
    readme += "- security headers\n";
    readme += "- request logging\n";
    readme += "- an `X-API: true` marker header for `/api` routes\n\n";

    readme += "Recommended middleware order for real applications:\n\n";
    readme += "```txt\n";
    readme += "CORS -> rate limit -> request logging -> security headers -> body limits -> auth -> routes\n";
    readme += "```\n\n";

    readme += "## Configuration\n\n";
    readme += "Start by copying the example environment file:\n\n";
    readme += "```bash\n";
    readme += "cp .env.example .env\n";
    readme += "```\n\n";

    readme += "Important defaults:\n\n";
    readme += "```dotenv\n";
    readme += "APP_NAME=" + projectName + "\n";
    readme += "APP_ENV=development\n";
    readme += "SERVER_PORT=8080\n";
    readme += "DATABASE_ENGINE=sqlite\n";
    readme += "DATABASE_SQLITE_PATH=storage/" + projectName + ".db\n";
    readme += "VIX_ORM_DIR=migrations\n";
    readme += "WEBSOCKET_ENABLED=false\n";
    readme += "```\n\n";

    readme += "Production defaults are documented in:\n\n";
    readme += "```txt\n";
    readme += "config/production.json\n";
    readme += "```\n\n";

    readme += "## Build manifest\n\n";
    readme += "This project uses `vix.app` as its application manifest.\n";
    readme += "Vix generates an internal CMake project automatically under:\n\n";
    readme += "```txt\n";
    readme += ".vix/generated/app/\n";
    readme += "```\n\n";

    readme += "Do not edit the generated CMake project manually. Edit `vix.app` instead.\n\n";

    readme += "## Common commands\n\n";
    readme += "```bash\n";
    readme += "vix dev\n";
    readme += "vix build\n";
    readme += "vix check --tests --run\n";
    readme += "vix tests\n";
    readme += "vix run\n";
    readme += "```\n\n";

    readme += "## Production workflow\n\n";
    readme += "The generated `vix.json` contains production-oriented tasks and settings for service, proxy, health checks, logs, deploys, and database defaults.\n\n";

    readme += "Useful commands:\n\n";
    readme += "```bash\n";
    readme += "vix build --preset release\n";
    readme += "vix check --tests --run\n";
    readme += "vix health local\n";
    readme += "vix logs\n";
    readme += "vix deploy\n";
    readme += "```\n\n";

    readme += "Depending on which production tools are installed in your Vix version, you may also use:\n\n";
    readme += "```bash\n";
    readme += "vix service install\n";
    readme += "vix proxy nginx init\n";
    readme += "vix doctor production\n";
    readme += "```\n\n";

    readme += "## ORM and migrations\n\n";
    readme += "The project includes a `migrations/` directory and `.env` defaults for `vix orm`.\n\n";

    readme += "Examples:\n\n";
    readme += "```bash\n";
    readme += "vix orm status\n";
    readme += "vix orm migrate\n";
    readme += "vix orm rollback --steps 1\n";
    readme += "```\n\n";

    readme += "## Static files\n\n";
    readme += "Static files live in:\n\n";
    readme += "```txt\n";
    readme += "public/\n";
    readme += "```\n\n";

    readme += "The generated app mounts `public/` at `/`.\n\n";

    readme += "## Templates\n\n";
    readme += "HTML templates can be placed in:\n\n";
    readme += "```txt\n";
    readme += "views/\n";
    readme += "```\n\n";

    readme += "The generated app configures:\n\n";
    readme += "```cpp\n";
    readme += "app.templates(\"views\");\n";
    readme += "```\n\n";

    readme += "## Notes\n\n";
    readme += "- Keep `main.cpp` minimal.\n";
    readme += "- Register routes through `RouteRegistry`.\n";
    readme += "- Register middleware through `MiddlewareRegistry`.\n";
    readme += "- Keep reusable helpers under `support/`.\n";
    readme += "- Put business logic under `application/` and `domain/` as the app grows.\n";
    readme += "- Put database, files, and external services under `infrastructure/`.\n";

    return readme;
  }

} // namespace vix::commands::new_cmd::templates
