/**
 *
 *  @file GlobalPackages.cpp
 *  @author Gaspard Kirira
 *
 *  Copyright 2025, Gaspard Kirira.  All rights reserved.
 *  https://github.com/vixcpp/vix
 *  Use of this source code is governed by a MIT license
 *  that can be found in the License file.
 *
 *  Vix.cpp
 */
#include <vix/cli/cmake/GlobalPackages.hpp>

#include <algorithm>
#include <cstdlib>
#include <fstream>
#include <optional>
#include <sstream>
#include <string>

#include <nlohmann/json.hpp>

namespace vix::cli::build
{
  namespace
  {
    static std::optional<std::string> home_dir()
    {
#ifdef _WIN32
      const char *home = std::getenv("USERPROFILE");
#else
      const char *home = std::getenv("HOME");
#endif
      if (!home || std::string(home).empty())
        return std::nullopt;

      return std::string(home);
    }

    static fs::path vix_root()
    {
      if (const auto home = home_dir(); home)
        return fs::path(*home) / ".vix";

      return fs::path(".vix");
    }

    static fs::path global_manifest_path()
    {
      return vix_root() / "global" / "installed.json";
    }

    static std::string dep_id_to_dir(std::string depId)
    {
      depId.erase(std::remove(depId.begin(), depId.end(), '@'), depId.end());
      std::replace(depId.begin(), depId.end(), '/', '.');
      return depId;
    }

    static std::string cmake_quote(const std::string &value)
    {
      std::string out;
      out.reserve(value.size() + 8);
      out.push_back('"');

      for (char c : value)
      {
        if (c == '\\')
          out += "\\\\";
        else if (c == '"')
          out += "\\\"";
        else
          out.push_back(c);
      }

      out.push_back('"');
      return out;
    }

    static bool is_header_only_package(const GlobalPackage &pkg)
    {
      return pkg.type == "header-only";
    }

    static fs::path package_include_path(const GlobalPackage &pkg)
    {
      return pkg.installedPath / pkg.includeDir;
    }

    static fs::path package_cmake_lists_path(const GlobalPackage &pkg)
    {
      return pkg.installedPath / "CMakeLists.txt";
    }

    static std::string package_binary_dir_name(const GlobalPackage &pkg)
    {
      std::string name = pkg.pkgDir;
      if (name.empty())
        name = "pkg";

      for (char &c : name)
      {
        if (c == '.' || c == '/' || c == '\\' || c == ':' || c == ' ')
          c = '_';
      }

      return name;
    }
  } // namespace

  std::vector<GlobalPackage> load_global_packages()
  {
    std::vector<GlobalPackage> out;

    const fs::path manifestPath = global_manifest_path();
    if (!fs::exists(manifestPath))
      return out;

    std::ifstream ifs(manifestPath);
    if (!ifs)
      return out;

    nlohmann::json root;
    ifs >> root;

    if (!root.is_object())
      return out;

    if (!root.contains("packages") || !root["packages"].is_array())
      return out;

    for (const auto &item : root["packages"])
    {
      if (!item.is_object())
        continue;

      if (!item.contains("id") || !item["id"].is_string())
        continue;

      if (!item.contains("installed_path") || !item["installed_path"].is_string())
        continue;

      GlobalPackage pkg;
      pkg.id = item["id"].get<std::string>();
      pkg.pkgDir = dep_id_to_dir(pkg.id);
      pkg.installedPath = fs::path(item["installed_path"].get<std::string>());

      if (item.contains("include") && item["include"].is_string())
        pkg.includeDir = item["include"].get<std::string>();

      if (item.contains("type") && item["type"].is_string())
        pkg.type = item["type"].get<std::string>();

      out.push_back(std::move(pkg));
    }

    return out;
  }

  std::string make_global_packages_cmake(const std::vector<GlobalPackage> &packages)
  {
    std::ostringstream out;

    out << "# Auto-generated by Vix\n";
    out << "# Global packages integration for vix build\n\n";

    if (packages.empty())
    {
      out << "# No global packages installed\n";
      return out.str();
    }

    for (const auto &pkg : packages)
    {
      if (pkg.installedPath.empty())
        continue;

      const fs::path includePath = package_include_path(pkg);
      const fs::path cmakeLists = package_cmake_lists_path(pkg);

      out << "# Package: " << pkg.id << "\n";

      if (!pkg.includeDir.empty())
      {
        out << "if (EXISTS " << cmake_quote(includePath.string()) << ")\n";
        out << "  include_directories(" << cmake_quote(includePath.string()) << ")\n";
        out << "endif()\n";
      }

      if (!is_header_only_package(pkg) && fs::exists(cmakeLists))
      {
        const std::string binDir =
            "${CMAKE_BINARY_DIR}/_vix_global/" + package_binary_dir_name(pkg);

        out << "if (EXISTS " << cmake_quote(cmakeLists.string()) << ")\n";
        out << "  add_subdirectory(\n";
        out << "    " << cmake_quote(pkg.installedPath.string()) << "\n";
        out << "    " << cmake_quote(binDir) << "\n";
        out << "    EXCLUDE_FROM_ALL\n";
        out << "  )\n";
        out << "endif()\n";
      }

      out << "\n";
    }

    return out.str();
  }

} // namespace vix::cli::build
