/**
 * @file WebReadmeTemplates.cpp
 * @author Gaspard Kirira
 *
 * Copyright 2025, Gaspard Kirira. All rights reserved.
 * https://github.com/vixcpp/vix
 * Use of this source code is governed by a MIT license
 * that can be found in the License file.
 */

#include <vix/cli/commands/new/templates/web/WebReadmeTemplates.hpp>

namespace vix::commands::new_cmd::templates
{

  std::string make_readme_web(const std::string &projectName)
  {
    std::string readme;
    readme.reserve(7600);

    readme += "# " + projectName + "\n\n";
    readme += "Server-rendered Vix web application.\n\n";

    readme += "This project is generated by:\n\n";
    readme += "```bash\n";
    readme += "vix new " + projectName + " --template web\n";
    readme += "```\n\n";

    readme += "It is designed for web applications that render HTML on the server using the Vix template engine.\n\n";

    readme += "## Quick start\n\n";
    readme += "```bash\n";
    readme += "cd " + projectName + "\n";
    readme += "cp .env.example .env\n";
    readme += "vix dev\n";
    readme += "```\n\n";

    readme += "Open:\n\n";
    readme += "```txt\n";
    readme += "http://127.0.0.1:8080\n";
    readme += "```\n\n";

    readme += "Check health:\n\n";
    readme += "```bash\n";
    readme += "curl http://127.0.0.1:8080/health\n";
    readme += "```\n\n";

    readme += "## Project layout\n\n";
    readme += "```txt\n";
    readme += "include/" + projectName + "/\n";
    readme += "  app/\n";
    readme += "    AppBootstrap.hpp\n";
    readme += "\n";
    readme += "src/\n";
    readme += "  main.cpp\n";
    readme += "  " + projectName + "/\n";
    readme += "    app/\n";
    readme += "      AppBootstrap.cpp\n";
    readme += "    presentation/\n";
    readme += "      controllers/\n";
    readme += "        PageController.hpp\n";
    readme += "        PageController.cpp\n";
    readme += "        HealthController.hpp\n";
    readme += "        HealthController.cpp\n";
    readme += "      middleware/\n";
    readme += "        MiddlewareRegistry.hpp\n";
    readme += "        MiddlewareRegistry.cpp\n";
    readme += "      routes/\n";
    readme += "        RouteRegistry.hpp\n";
    readme += "        RouteRegistry.cpp\n";
    readme += "\n";
    readme += "views/\n";
    readme += "  base.html\n";
    readme += "  header.html\n";
    readme += "  index.html\n";
    readme += "  dashboard.html\n";
    readme += "\n";
    readme += "public/\n";
    readme += "  app.css\n";
    readme += "  app.js\n";
    readme += "\n";
    readme += "storage/\n";
    readme += "tests/\n";
    readme += "\n";
    readme += ".env\n";
    readme += ".env.example\n";
    readme += "vix.app\n";
    readme += "vix.json\n";
    readme += "README.md\n";
    readme += "```\n\n";

    readme += "## Routes\n\n";
    readme += "Generated routes:\n\n";
    readme += "```txt\n";
    readme += "GET /             HTML home page\n";
    readme += "GET /dashboard    HTML dashboard page\n";
    readme += "GET /health       JSON health check\n";
    readme += "```\n\n";

    readme += "Routes are registered from:\n\n";
    readme += "```txt\n";
    readme += "src/" + projectName + "/presentation/routes/RouteRegistry.cpp\n";
    readme += "```\n\n";

    readme += "## Templates\n\n";
    readme += "Templates live in:\n\n";
    readme += "```txt\n";
    readme += "views/\n";
    readme += "```\n\n";

    readme += "The generated app configures the template directory in `AppBootstrap`:\n\n";
    readme += "```cpp\n";
    readme += "app.templates(\"views\");\n";
    readme += "```\n\n";

    readme += "The generated templates show:\n\n";
    readme += "- layouts with `{% extends \"base.html\" %}`\n";
    readme += "- blocks with `{% block content %}`\n";
    readme += "- partials with `{% include \"header.html\" %}`\n";
    readme += "- variables with `{{ title }}`\n";
    readme += "- loops with `{% for feature in features %}`\n\n";

    readme += "## Static files\n\n";
    readme += "Static assets live in:\n\n";
    readme += "```txt\n";
    readme += "public/\n";
    readme += "```\n\n";

    readme += "The generated app mounts `public/` at `/`:\n\n";
    readme += "```cpp\n";
    readme += "app.static_dir(\"public\", \"/\");\n";
    readme += "```\n\n";

    readme += "## Entry point\n\n";
    readme += "`main.cpp` stays minimal:\n\n";

    readme += "```cpp\n";
    readme += "#include <" + projectName + "/app/AppBootstrap.hpp>\n\n";
    readme += "int main()\n";
    readme += "{\n";
    readme += "  " + projectName + "::app::AppBootstrap bootstrap;\n";
    readme += "  return bootstrap.run();\n";
    readme += "}\n";
    readme += "```\n\n";

    readme += "## Bootstrap flow\n\n";
    readme += "```txt\n";
    readme += "main.cpp\n";
    readme += "  -> AppBootstrap\n";
    readme += "      -> vix::config::Config\n";
    readme += "      -> vix::App\n";
    readme += "      -> app.templates(\"views\")\n";
    readme += "      -> app.static_dir(\"public\", \"/\")\n";
    readme += "      -> MiddlewareRegistry\n";
    readme += "      -> RouteRegistry\n";
    readme += "      -> app.run(cfg)\n";
    readme += "```\n\n";

    readme += "## Configuration\n\n";
    readme += "Start by copying the example environment file:\n\n";
    readme += "```bash\n";
    readme += "cp .env.example .env\n";
    readme += "```\n\n";

    readme += "Important defaults:\n\n";
    readme += "```dotenv\n";
    readme += "APP_NAME=" + projectName + "\n";
    readme += "APP_ENV=development\n";
    readme += "APP_TEMPLATE=web\n";
    readme += "SERVER_PORT=8080\n";
    readme += "PUBLIC_PATH=public\n";
    readme += "VIEWS_PATH=views\n";
    readme += "```\n\n";

    readme += "## Configuration sources\n\n";
    readme += "This template intentionally keeps one Vix production configuration source:\n\n";
    readme += "```txt\n";
    readme += "vix.json\n";
    readme += "```\n\n";

    readme += "`vix.json` describes what Vix needs to orchestrate the project:\n\n";
    readme += "- service generation\n";
    readme += "- Nginx proxy configuration\n";
    readme += "- health checks\n";
    readme += "- deployment workflow\n";
    readme += "- logs\n";
    readme += "- production ports\n";
    readme += "- required environment variables\n";
    readme += "- web template and public file settings\n\n";

    readme += "Runtime values and secrets stay in:\n\n";
    readme += "```txt\n";
    readme += ".env\n";
    readme += ".env.example\n";
    readme += "```\n\n";

    readme += "Rule:\n\n";
    readme += "```txt\n";
    readme += "vix.json      -> Vix orchestration config\n";
    readme += ".env          -> local runtime values and secrets\n";
    readme += ".env.example  -> documented expected variables\n";
    readme += "```\n\n";

    readme += "This web template does not generate `config/production.json` to avoid two competing production configuration files.\n\n";

    readme += "## Common commands\n\n";
    readme += "```bash\n";
    readme += "vix dev\n";
    readme += "vix build\n";
    readme += "vix check --tests --run\n";
    readme += "vix tests\n";
    readme += "vix run\n";
    readme += "```\n\n";

    readme += "## Production workflow\n\n";
    readme += "`vix.json` is the production control file for Vix. It contains tasks and settings for service, proxy, health checks, logs, deploys, ports, environment requirements, and web runtime defaults.\n\n";
    readme += "Useful commands:\n\n";
    readme += "```bash\n";
    readme += "vix build --preset release\n";
    readme += "vix check --tests --run\n";
    readme += "vix env check --production\n";
    readme += "vix health\n";
    readme += "vix logs\n";
    readme += "vix deploy\n";
    readme += "```\n\n";

    readme += "Depending on which production tools are installed in your Vix version, you may also use:\n\n";
    readme += "```bash\n";
    readme += "vix service install\n";
    readme += "vix proxy nginx init\n";
    readme += "vix doctor production\n";
    readme += "```\n\n";

    readme += "## Notes\n\n";
    readme += "- Use `views/` for HTML templates.\n";
    readme += "- Use `public/` for CSS, JS, images, and static files.\n";
    readme += "- Keep route registration inside `RouteRegistry`.\n";
    readme += "- Keep HTML page handlers inside `PageController`.\n";
    readme += "- Keep `main.cpp` minimal.\n";

    return readme;
  }

} // namespace vix::commands::new_cmd::templates
