/**
 * @file WebTestTemplates.cpp
 * @author Gaspard Kirira
 *
 * Copyright 2025, Gaspard Kirira.  All rights reserved.
 * https://github.com/vixcpp/vix
 * Use of this source code is governed by a MIT license
 * that can be found in the License file.
 */

#include <vix/cli/commands/new/templates/web/WebTestTemplates.hpp>

#include <string>

namespace vix::commands::new_cmd::templates
{

  std::string make_web_basic_test_cpp(const std::string &projectName)
  {
    std::string s;
    s.reserve(2400);

    s += "/**\n";
    s += " * @file test_basic.cpp\n";
    s += " * @brief Basic tests for the " + projectName + " web application.\n";
    s += " *\n";
    s += " * This file is generated by the Vix web template. It provides a\n";
    s += " * minimal test executable to validate that the test runner is wired\n";
    s += " * correctly and that the generated project can compile test targets.\n";
    s += " */\n\n";

    s += "#include <string>\n\n";
    s += "#include <vix/tests/tests.hpp>\n\n";

    s += "/**\n";
    s += " * @brief Run the generated web test suite.\n";
    s += " *\n";
    s += " * The test executable owns its own main function and must not include\n";
    s += " * the application main.cpp file.\n";
    s += " *\n";
    s += " * @return Process exit code returned by the Vix test runner.\n";
    s += " */\n";
    s += "int main()\n";
    s += "{\n";
    s += "  using namespace vix::tests;\n\n";

    s += "  auto &registry = TestRegistry::instance();\n";
    s += "  registry.clear();\n\n";

    s += "  registry.add(TestCase(\"" + projectName + " web basic test\", []\n";
    s += "  {\n";
    s += "    Assert::equal(2 + 2, 4);\n";
    s += "  }));\n\n";

    s += "  registry.add(TestCase(\"" + projectName + " web template name is available\", []\n";
    s += "  {\n";
    s += "    const char *name = \"" + projectName + "\";\n";
    s += "    Assert::truthy(name != nullptr);\n";
    s += "  }));\n\n";

    s += "  registry.add(TestCase(\"" + projectName + " web route names are stable\", []\n";
    s += "  {\n";
    s += "    Assert::equal(std::string(\"/\"), std::string(\"/\"));\n";
    s += "    Assert::equal(std::string(\"/dashboard\"), std::string(\"/dashboard\"));\n";
    s += "    Assert::equal(std::string(\"/health\"), std::string(\"/health\"));\n";
    s += "  }));\n\n";

    s += "  return TestRunner::run_all_and_exit();\n";
    s += "}\n";

    return s;
  }

  std::string make_web_tests_manifest(const std::string &projectName)
  {
    std::string s;
    s.reserve(1600);

    s += "# Vix web test manifest\n";
    s += "#\n";
    s += "# This file describes the generated test executable for the web app.\n";
    s += "# The test target is intentionally separate from the application target.\n";
    s += "# Do not include ../src/main.cpp here because tests define their own main().\n\n";

    s += "name = \"" + projectName + "_web_tests\"\n";
    s += "type = \"executable\"\n";
    s += "standard = \"c++20\"\n";
    s += "output_dir = \"bin\"\n\n";

    s += "sources = [\n";
    s += "  \"test_basic.cpp\",\n";
    s += "]\n\n";

    s += "include_dirs = [\n";
    s += "  \"../include\",\n";
    s += "  \"../src\",\n";
    s += "]\n\n";

    s += "defines = [\n";
    s += "  \"VIX_WEB_TESTS=1\",\n";
    s += "  \"VIX_APP_NAME=\\\"" + projectName + "\\\"\",\n";
    s += "]\n\n";

    s += "packages = [\n";
    s += "  \"vix\",\n";
    s += "]\n\n";

    s += "links = [\n";
    s += "  \"vix::vix\",\n";
    s += "]\n";

    return s;
  }

} // namespace vix::commands::new_cmd::templates
